name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      name:
        description: "Input descriptions"
        type: string
        default: "Prem"
        required: false
    secrets:
      access-token:
        description: "Secret descriptions"
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  logs-context-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display Github Contexts
        run: echo '${{ toJson(github) }}'

      - name: Display name input
        run: echo ${{ inputs.name }}

      - name: Display access-token secret
        run: echo ${{ secrets.access-token }}
